name: Build and Push Image
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write # needed to push image to ghcr.io

    steps:
      -
        name: Checkout git repo
        uses: actions/checkout@v3
      - name:  Test file
        run: |
          ls
          ls -alh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        if: |
          ${{ secrets.DOCKERHUB_USERNAME }}
          ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jobbee-api:latest